// const Transaction = require("../../model/transaction");

const expenses = [
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2022-09-20'),
      amount: 800,
      description: 'Groceries',
      currency: 'INR',
      category: 5,
      type: 2,
      status: 12,
      method: 7,
      card: 'Visa',
      bank: 'Chase Bank',
      merchant: 'Supermarket',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2022-11-10'),
      amount: 2500,
      description: 'Dinner with friends',
      currency: 'INR',
      category: 9,
      type: 1,
      status: 3,
      method: 17,
      card: 'Mastercard',
      bank: 'Wells Fargo',
      merchant: 'Restaurant',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2022-12-05'),
      amount: 5500,
      description: 'Holiday accommodation',
      currency: 'INR',
      category: 14,
      type: 3,
      status: 6,
      method: 5,
      card: 'American Express',
      bank: 'CitiBank',
      merchant: 'Hotel',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-01-12'),
      amount: 120,
      description: 'Books',
      currency: 'INR',
      category: 3,
      type: 2,
      status: 10,
      method: 9,
      card: 'Visa',
      bank: 'US Bank',
      merchant: 'Online Bookstore',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-02-28'),
      amount: 9200,
      description: 'Vacation expenses',
      currency: 'INR',
      category: 17,
      type: 1,
      status: 2,
      method: 11,
      card: 'Discover',
      bank: 'Wells Fargo',
      merchant: 'Travel Agency',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-04-15'),
      amount: 75,
      description: 'Movie tickets',
      currency: 'INR',
      category: 11,
      type: 3,
      status: 15,
      method: 19,
      card: 'Visa',
      bank: 'Bank of America',
      merchant: 'Cinema',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-06-01'),
      amount: 3100,
      description: 'Home improvement',
      currency: 'INR',
      category: 6,
      type: 2,
      status: 8,
      method: 16,
      card: 'Mastercard',
      bank: 'Chase Bank',
      merchant: 'Home Improvement Store',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-07-18'),
      amount: 95,
      description: 'Gym membership',
      currency: 'INR',
      category: 10,
      type: 1,
      status: 5,
      method: 4,
      card: 'American Express',
      bank: 'CitiBank',
      merchant: 'Fitness Center',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-09-03'),
      amount: 680,
      description: 'Restaurant lunch',
      currency: 'INR',
      category: 8,
      type: 3,
      status: 13,
      method: 18,
      card: 'Visa',
      bank: 'US Bank',
      merchant: 'Restaurant',
      comments: '',
    },
    {
      user_id: '64969239bf68911b25345745',
      date: new Date('2023-10-21'),
      amount: 4200,
      description: 'Electronics purchase',
      currency: 'INR',
      category: 16,
      type: 2,
      status: 4,
      method: 14,
      card: 'Discover',
      bank: 'Bank of America',
      merchant: 'Electronics Store',
      comments: '',
    }
  ];
  
  
  console.log(expenses);
  

// const test_data = [];

// for (obj in expenses) {
//     Transaction.create(obj);
// }

// Transaction.create({
//     user_id: req.user.user_id,
//     date: date,
//     amount: amount,
//     description: description,
//     currency: currency,
//     category: category,
//     type: type,
//     status: status,
//     method: method,
//     card: card,
//     bank: bank,
//     merchant: merchant,
//     comments: comments,
// });